/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function plus(a: number, b: number): number
export type JsAlgo = Algo
export class Algo {
  constructor(name: string)
  hash(v: string): string
  getName(): string
}
