/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function plus(a: number, b: number): number
export type JsAlgo = Algo
export class Algo {
  constructor(name: string)
  hash(v: string): string
  getName(): string
}
export type JsMatrix = Matrix
export class Matrix {
  constructor(data: Array<Array<number>>)
  mul(other: Matrix): this
  multiply(other: Array<Array<number>>): this
  display(): string
}
